//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 

namespace KwasantCore.Managers.APIManager.CalDAV
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DAV:")]
    [System.Xml.Serialization.XmlRootAttribute("multistatus", Namespace = "DAV:", IsNullable = false)]
    public partial class MultiStatus
    {

        private MultiStatusResponse[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("response")]
        public MultiStatusResponse[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DAV:")]
    public partial class MultiStatusResponse
    {
        /// <remarks/>
        [XmlElement("href")]
        public string Href { get; set; }

        /// <remarks/>
        [XmlElement("propstat")]
        public multistatusResponsePropstat[] PropStat { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DAV:")]
    public partial class multistatusResponsePropstat
    {
        /// <remarks/>
        [XmlElement("status")]
        public string Status { get; set; }

        /// <remarks/>
        [XmlElement("prop")]
        public MultiStatusResponsePropstatProp Prop { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DAV:")]
    public partial class MultiStatusResponsePropstatProp
    {
        /// <remarks/>
        [XmlElement("getetag")]
        public string Detetag { get; set; }

        /// <remarks/>
        [XmlElement("calendar-data", Namespace = "urn:ietf:params:xml:ns:caldav")]
        public string CalendarData { get; set; }
    }

}
