namespace Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FixUpPastSimpleEmails : DbMigration
    {
        public override void Up()
        {
            Sql(@"UPDATE 
dbo.Envelopes 
SET TemplateDescription = 'A booker sent the following email to these recipients:' + STUFF((SELECT ', ' + Address
    from Recipients
	inner join EmailAddresses on EmailAddressID = EmailAddresses.Id 
	WHERE Recipients.EmailID = Emails.Id AND Address != 'kwasantoutbound@gmail.com'
        FOR XML PATH(''), TYPE)
    .value('.','NVARCHAR(MAX)'),1,2,'') + '<br/></br>' + ISNULL(Emails.HTMLText,'')
FROM dbo.Envelopes
INNER JOIN Emails on dbo.Envelopes.EmailID = Emails.Id
WHERE TemplateName = '7063998f-0560-4a3e-9fbe-88432892286b'

UPDATE Envelopes
SET TemplateDescription = 'This email was generated by the template ''Negotiation request'' and was sent to ''' + STUFF((SELECT ', ' + Address
    from Recipients
	inner join EmailAddresses on EmailAddressID = EmailAddresses.Id 
	WHERE Recipients.EmailID = Emails.Id AND Address != 'kwasantoutbound@gmail.com'
        FOR XML PATH(''), TYPE)
    .value('.','NVARCHAR(MAX)'),1,2,'') 
	+ '''<br/>Extra information:' 
	+ '<br/>Body: ''' + ISNULL(Emails.HTMLText,'') + ''''
	+ '<br/>Questions: '
	+ STUFF((SELECT '  <br/>- ' + Questions.Text
		from Negotiations
		inner join Questions on NegotiationId = Negotiations.Id 
		WHERE Negotiations.BookingRequestID = Emails.ConversationId OR Negotiations.BookingRequestID = Emails.Id
			FOR XML PATH(''), TYPE)
		.value('.','NVARCHAR(MAX)'),1,2,' ')
FROM dbo.Envelopes
INNER JOIN Emails on dbo.Envelopes.EmailID = Emails.Id
WHERE (TemplateName = '6a59b7f4-9f12-47ea-8fa9-be1b96733b3d' OR TemplateName = '09a7919f-e5d3-4c98-b6b8-d8ac6171401d')
and ConversationId is not null
");
        }
        
        public override void Down()
        {
        }
    }
}
