// <auto-generated />
namespace shnexy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class tweak22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tweak22));
        
        string IMigrationMetadata.Id
        {
            get { return "201402092325334_tweak22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
