// <auto-generated />
namespace shnexy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class topic_tweak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topic_tweak));
        
        string IMigrationMetadata.Id
        {
            get { return "201401230722252_topic_tweak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
